/* 
 * Material didático destinado ao curso
 * de Programação Orientada a Objetos do 
 * Bacharelado em Ciência da Computação 
 * do IFNMG - Câmpus Montes Claros
 */
package io.github.guisso.poo.login.gui;

import io.github.guisso.poo.login.entity.Usuario;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;

/**
 *
 * @author Luis Guisso <luis dot guisso at ifnmg dot edu dot br>
 * @version 0.0.1, 09/08/2021
 */
public class Principal extends javax.swing.JFrame {

    private Usuario usuarioSistema;

    /**
     * Creates new form Principal
     * @param usuarioSistema Dados do usuário para personalização da UI
     */
    public Principal(Usuario usuarioSistema) {
        this.usuarioSistema = usuarioSistema;
        initComponents();

        // Configuração da janela diante do perfil de administrador
//        if(usuarioSistema.getAdministrador()) { ... }
//        System.out.println("admin? " + usuarioSistema.getAdministrador());
        mnuAdministrador.setEnabled(usuarioSistema.getAdministrador());
        mnuCadastroUsuario.setEnabled(usuarioSistema.getAdministrador());
        
        // Personalização do título da janela
        setTitle("Sistema :: " + usuarioSistema.getNome());

        // Centralização da janela
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrPrincipal = new javax.swing.JScrollPane();
        dskPrincipal = new javax.swing.JDesktopPane();
        mnuBarra = new javax.swing.JMenuBar();
        mnuArquivo = new javax.swing.JMenu();
        mnuCadastro = new javax.swing.JMenu();
        mnuCadastroUsuario = new javax.swing.JMenuItem();
        mnuAdministrador = new javax.swing.JMenuItem();
        mnuSair = new javax.swing.JMenuItem();
        mnuAjuda = new javax.swing.JMenu();
        mnuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema");

        scrPrincipal.setBackground(new java.awt.Color(60, 63, 65));
        scrPrincipal.setBorder(null);
        scrPrincipal.setHorizontalScrollBar(null);

        dskPrincipal.setBackground(new java.awt.Color(60, 63, 65));
        dskPrincipal.setAutoscrolls(true);

        javax.swing.GroupLayout dskPrincipalLayout = new javax.swing.GroupLayout(dskPrincipal);
        dskPrincipal.setLayout(dskPrincipalLayout);
        dskPrincipalLayout.setHorizontalGroup(
            dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        dskPrincipalLayout.setVerticalGroup(
            dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );

        scrPrincipal.setViewportView(dskPrincipal);

        mnuArquivo.setMnemonic('A');
        mnuArquivo.setText("Arquivo");

        mnuCadastro.setMnemonic('c');
        mnuCadastro.setText("Cadastro");

        mnuCadastroUsuario.setMnemonic('u');
        mnuCadastroUsuario.setText("Usuario");
        mnuCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastroUsuarioActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuCadastroUsuario);

        mnuArquivo.add(mnuCadastro);

        mnuAdministrador.setMnemonic('a');
        mnuAdministrador.setText("Administrador");
        mnuAdministrador.setEnabled(false);
        mnuArquivo.add(mnuAdministrador);

        mnuSair.setMnemonic('r');
        mnuSair.setText("Sair");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        mnuArquivo.add(mnuSair);

        mnuBarra.add(mnuArquivo);

        mnuAjuda.setMnemonic('u');
        mnuAjuda.setText("Ajuda");
        mnuAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAjudaActionPerformed(evt);
            }
        });

        mnuSobre.setMnemonic('s');
        mnuSobre.setText("Sobre");
        mnuAjuda.add(mnuSobre);

        mnuBarra.add(mnuAjuda);

        setJMenuBar(mnuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastroUsuarioActionPerformed
//        CadastroUsuario cadastroUsuario = new CadastroUsuario();
//        cadastroUsuario.setVisible(true);
//        dskPrincipal.add(cadastroUsuario);

        anexarJanela(CadastroUsuario.getInstance());
    }//GEN-LAST:event_mnuCadastroUsuarioActionPerformed

    private void mnuAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAjudaActionPerformed
        // Exemplo de criação de uma nova janela na área de trabalho do programa
//        JanelaSobre janelaSobre = new JanelaSobre();
//        janelaSobre.setVisible(true);
//        dskPrincipal.add(janelaSobre);
    }//GEN-LAST:event_mnuAjudaActionPerformed

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_mnuSairActionPerformed

    private void anexarJanela(JInternalFrame janela) {
        if (!janela.isVisible()) {
            dskPrincipal.add(janela);
            janela.setVisible(true);
        }

        try {
            // Restaura, se minimizada
            janela.setIcon(false);
            // Move o foco
            janela.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Traz para o primeiro plano
        janela.toFront();
    }

    //
    // O método main() não é requerido e nem desejável pois esta janela não 
    // funciona de forma independente do programa principal
    //
//    public static void main(String args[]) {
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Principal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskPrincipal;
    private javax.swing.JMenuItem mnuAdministrador;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenu mnuArquivo;
    private javax.swing.JMenuBar mnuBarra;
    private javax.swing.JMenu mnuCadastro;
    private javax.swing.JMenuItem mnuCadastroUsuario;
    private javax.swing.JMenuItem mnuSair;
    private javax.swing.JMenuItem mnuSobre;
    private javax.swing.JScrollPane scrPrincipal;
    // End of variables declaration//GEN-END:variables
}
